# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    translator:
        fallbacks: [fr]

    # Note that the session will be started ONLY if you read or write from it.
    session: true
    rate_limiter:
        login:
            policy: token_bucket
            limit: 5
            rate: { interval: '15 minutes', amount: 5 }

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
