<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260816010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add persisted locales and normalized French/English workshop translations.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE skillspot_user ADD preferred_locale VARCHAR(2) DEFAULT 'fr' NOT NULL");
        $this->addSql("ALTER TABLE skillspot_user ADD CONSTRAINT valid_user_preferred_locale CHECK (preferred_locale IN ('fr', 'en'))");
        $this->addSql('CREATE TABLE workshop_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workshop_id INT NOT NULL, locale VARCHAR(2) NOT NULL, title VARCHAR(160) NOT NULL, slug VARCHAR(190) NOT NULL, description TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_89362E211FDCE57C ON workshop_translation (workshop_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_workshop_translation_locale ON workshop_translation (workshop_id, locale)');
        $this->addSql('CREATE UNIQUE INDEX uniq_workshop_translation_slug ON workshop_translation (locale, slug)');
        $this->addSql("ALTER TABLE workshop_translation ADD CONSTRAINT valid_workshop_translation_locale CHECK (locale IN ('fr', 'en'))");
        $this->addSql('ALTER TABLE workshop_translation ADD CONSTRAINT FK_89362E211FDCE57C FOREIGN KEY (workshop_id) REFERENCES workshop (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("INSERT INTO workshop_translation (workshop_id, locale, title, slug, description) SELECT id, 'fr', title, slug, description FROM workshop");
        $this->addSql("INSERT INTO workshop_translation (workshop_id, locale, title, slug, description) SELECT id, 'en', title, slug, description FROM workshop");
        $this->addSql('DROP INDEX uniq_workshop_slug');
        $this->addSql('ALTER TABLE workshop DROP title');
        $this->addSql('ALTER TABLE workshop DROP slug');
        $this->addSql('ALTER TABLE workshop DROP description');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE workshop ADD title VARCHAR(160) DEFAULT NULL');
        $this->addSql('ALTER TABLE workshop ADD slug VARCHAR(190) DEFAULT NULL');
        $this->addSql('ALTER TABLE workshop ADD description TEXT DEFAULT NULL');
        $this->addSql("UPDATE workshop w SET title = t.title, slug = t.slug, description = t.description FROM workshop_translation t WHERE t.workshop_id = w.id AND t.locale = 'fr'");
        $this->addSql('ALTER TABLE workshop ALTER title SET NOT NULL');
        $this->addSql('ALTER TABLE workshop ALTER slug SET NOT NULL');
        $this->addSql('ALTER TABLE workshop ALTER description SET NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_workshop_slug ON workshop (slug)');
        $this->addSql('DROP TABLE workshop_translation');
        $this->addSql('ALTER TABLE skillspot_user DROP CONSTRAINT valid_user_preferred_locale');
        $this->addSql('ALTER TABLE skillspot_user DROP preferred_locale');
    }
}
