<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260815230000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the SkillSpot identity, workshop, booking and async messaging model.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE skillspot_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, roles JSON NOT NULL, email VARCHAR(180) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, password VARCHAR(255) NOT NULL, verified BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON skillspot_user (email)');
        $this->addSql('CREATE TABLE organizer_application (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, applicant_id INT NOT NULL, reviewed_by_id INT DEFAULT NULL, motivation TEXT NOT NULL, status VARCHAR(20) NOT NULL, decision_note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A6526A5E97139001 ON organizer_application (applicant_id)');
        $this->addSql('CREATE INDEX IDX_A6526A5EFC6B21F1 ON organizer_application (reviewed_by_id)');
        $this->addSql('CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('CREATE TABLE workshop (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, title VARCHAR(160) NOT NULL, slug VARCHAR(190) NOT NULL, description TEXT NOT NULL, category VARCHAR(30) NOT NULL, level VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9B6F02C47E3C61F9 ON workshop (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_workshop_slug ON workshop (slug)');
        $this->addSql('CREATE TABLE workshop_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workshop_id INT NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, capacity INT NOT NULL, mode VARCHAR(20) NOT NULL, location VARCHAR(255) DEFAULT NULL, meeting_url VARCHAR(500) DEFAULT NULL, status VARCHAR(20) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_920BC7C31FDCE57C ON workshop_session (workshop_id)');
        $this->addSql('ALTER TABLE workshop_session ADD CONSTRAINT valid_session_schedule CHECK (ends_at > starts_at)');
        $this->addSql('ALTER TABLE workshop_session ADD CONSTRAINT valid_session_capacity CHECK (capacity BETWEEN 1 AND 200)');
        $this->addSql('CREATE TABLE booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, attendee_id INT NOT NULL, session_id INT NOT NULL, status VARCHAR(20) NOT NULL, attendance VARCHAR(20) NOT NULL, queued_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reminder_sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E00CEDDEBCFD782A ON booking (attendee_id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDE613FECDF ON booking (session_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_booking_attendee_session ON booking (attendee_id, session_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE organizer_application ADD CONSTRAINT FK_A6526A5E97139001 FOREIGN KEY (applicant_id) REFERENCES skillspot_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organizer_application ADD CONSTRAINT FK_A6526A5EFC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES skillspot_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES skillspot_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE workshop ADD CONSTRAINT FK_9B6F02C47E3C61F9 FOREIGN KEY (owner_id) REFERENCES skillspot_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE workshop_session ADD CONSTRAINT FK_920BC7C31FDCE57C FOREIGN KEY (workshop_id) REFERENCES workshop (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEBCFD782A FOREIGN KEY (attendee_id) REFERENCES skillspot_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE613FECDF FOREIGN KEY (session_id) REFERENCES workshop_session (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE workshop_session');
        $this->addSql('DROP TABLE workshop');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE organizer_application');
        $this->addSql('DROP TABLE skillspot_user');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
